#!/bin/bash -x

   echo "check the email pattern"
   #adding @ part 
   #adding . part
   #adding optional part 
   pat="^[0-9a-zA-Z]+([._+-][0-9a-zA-z]+)?@[0-9a-zA-Z]+.[a-zA-Z]{2,4}"
   read any
   if [[ $any =~ $pat ]];
   then
     echo "valid";
   else
     echo "invalid";
   fi

