#!/bin/bash -x

   echo "check the email pattern"
   #adding @ part 
   pat="^[0-9a-zA-Z]+@[0-9a-zA-Z]+"
   read any
   if [[ $any =~ $pat ]];
   then
     echo "valid";
   else
     echo "invalid";
   fi

